const { models } = require('../database');

// Populate Categories
const categories = await models.Categories.bulkCreate([
    // Alphabetize
    { name: "African" },
    { name: "American" },
    { name: "Appetizer" },
    { name: "Baked" },
    { name: "Beverage" },
    { name: "Bread" },
    { name: "Breakfast" },
    { name: "Caribbean" },
    { name: "Chinese" },
    { name: "Cold" },
    { name: "Creamy"},
    { name: "Crispy" },
    { name: "Crunchy" },
    { name: "Dairy-Free" },
    { name: "Desert" },
    { name: "Deep Fried"},
    { name: "Dinner" },
    { name: "Dry" },
    { name: "French" },
    { name: "Fried" },
    { name: "Glutten-Free" },
    { name: "Greek" },
    { name: "High Carb" },
    { name: "High Fiber" },
    { name: "High Protein" },
    { name: "Hot" },
    { name: "Indian" },
    { name: "Italian" },
    { name: "Japanese" },
    { name: "Keto" },
    { name: "Korean" },
    { name: "Low Carb" },
    { name: "Low Sugar" },
    { name: "Lunch" },
    { name: "Mediterranean" },
    { name: "Mexican" },
    { name: "Middle Eastern" },
    { name: "Salad" },
    { name: "Salty" },
    { name: "Sauce" },
    { name: "Soup" },
    { name: "Smoked" },
    { name: "Snack" },
    { name: "Spicy" },
    { name: "Sweet" },
    { name: "Thai" },
    { name: "Vegan" },
    { name: "Vegetarian" },
    { name: "Vietnamese" },
    { name: "Quick" },
])

// Populate Dietary Restrictions 
models.DietaryRestrictions.bulkCreate([
    { name: "Glutten-Free" },
    { name: "Vegan" },
    { name: "Vegetarian" },
    { name: "Pescetarian" },
    { name: "Dairy-Free" },
    { name: "Halal" },
    { name: "Kosher" },
    { name: "Raw Food" },
    { name: "Keto" },
    { name: "Paleo" },
    { name: "Low-Carb" },
])

// Populate Allergies
models.Allergies.bulkCreate([
    { name: "Eggs" },
    { name: "Dairy" },
    { name: "Wheat" },
    { name: "Tree Nuts" },
    { name: "Peanuts" },
    { name: "Soy" },
    { name: "Shellfish" },
    { name: "Sesame" },
    { name: "Fish" }
])

// Populate Questions
const questions = await models.Questionnaire.bulkCreate([
    { question: "What temperature are looking to consume?" },
    { question: "Dry or Crispy" },
    { question: "Heavy or Light" },
    { question: "Spicy or Sweet" },
    { question: "What cuisine sounds most appealing?" },
    { question: "Sweet, salty or both?" },
    { question: "What time-of-day meal do you want?" },
    { question: "Fried or Baked?" },
    { question: "Quick cook time?" },
    { question: "Soup or Salad?"},
    { question: "Crunchy or Creamy?"},
    { question: "Want something high in Fiber or Protein?" },
])

// Populate QuestionnaireCategory 
models.QuestionnaireCategory.bulkCreate = ([
    { QuestionnaireId: questions[0].id, CategoryIds: categories[9].id },
    { QuestionnaireId: questions[0].id, CategoryIds: categories[25].id },
    { QuestionnaireId: questions[1].id, CategoryIds: categories[16].id },
    { QuestionnaireId: questions[1].id, CategoryIds: categories[11].id },
    { QuestionnaireId: questions[2].id, CategoryIds: categories[24].id },
    { QuestionnaireId: questions[2].id, CategoryIds: categories[42].id },
    { QuestionnaireId: questions[3].id, CategoryIds: categories[43].id },
    { QuestionnaireId: questions[3].id, CategoryIds: categories[44].id },
    { QuestionnaireId: questions[4].id, CategoryIds: categories[35].id },
    { QuestionnaireId: questions[4].id, CategoryIds: categories[45].id },
    { QuestionnaireId: questions[4].id, CategoryIds: categories[27].id },
    { QuestionnaireId: questions[4].id, CategoryIds: categories[8].id },
    { QuestionnaireId: questions[5].id, CategoryIds: categories[44].id },
    { QuestionnaireId: questions[5].id, CategoryIds: categories[38].id },
    { QuestionnaireId: questions[6].id, CategoryIds: categories[6].id },
    { QuestionnaireId: questions[6].id, CategoryIds: categories[16].id },
    { QuestionnaireId: questions[6].id, CategoryIds: categories[33].id },
    { QuestionnaireId: questions[6].id, CategoryIds: categories[14].id },
    { QuestionnaireId: questions[7].id, CategoryIds: categories[19].id },
    { QuestionnaireId: questions[7].id, CategoryIds: categories[3].id },
    { QuestionnaireId: questions[8].id, CategoryIds: categories[49].id },
    { QuestionnaireId: questions[9].id, CategoryIds: categories[37].id },
    { QuestionnaireId: questions[9].id, CategoryIds: categories[40].id },
    { QuestionnaireId: questions[10].id, CategoryIds: categories[10].id },
    { QuestionnaireId: questions[10].id, CategoryIds: categories[12].id },
    { QuestionnaireId: questions[11].id, CategoryIds: categories[22].id },
    { QuestionnaireId: questions[11].id, CategoryIds: categories[23].id },
])